### ISSUE TITLE
ENOBUFS on BSD, MacOS

### ISSUE THREAD

**Issue by lnicola** [joshtriplett/io-mux#7]
Spawned from #6.

`io-mux` works fine on Linux, but not very well on BSD. It seems that writing to blocking Unix domain (and UDP) sockets will return `ENOBUFS` when there's no buffer space available. The documentation is misleading:

> If no messages [sic] space is available at the socket to hold the message to be transmitted, then `send()` normally blocks, unless the socket has been placed in non-blocking I/O mode.

See https://stackoverflow.com/questions/16555101/sendto-dgrams-do-not-block-for-enobufs-on-osx. Apparently even `select()` returns the socket as writable, so there's no way to handle this even if you control the sender (which `io-mux` doesn't). The linked mailing list threads suggest calling `nanosleep` on error.

A `SOCK_SEQPACKET` might work as an alternative, but I've never used them.

**Comment by joshtriplett** [comment]
`SOCK_SEQPACKET` is unfortunately not a solution, as it's connection-oriented just like `SOCK_STREAM`, and only supports one-to-one connections. `io-mux` relies on the many-to-one connections of `SOCK_DGRAM`.

This seems very unfortunate. Datagrams still have the *ordering* requirements on FreeBSD and macOS, but it does indeed look like `write` does not have the expected blocking semantics on either BSD or macOS, and will return an error rather than blocking if the buffer fills up. It's not *completely* a deal-breaker, as the reading process may be able to keep up, but introduces a possibility of error.

If there's some way to configure a socket for the expected blocking behavior on BSD or macOS, I'd be happy to change io-mux to do so.

In the absence of some kind of solution to get the expected blocking behavior, I can see two options:

1) Don't support platforms where `write` on a socket will error rather than blocking. Unfortunate, after the efforts that @Freaky went to to make it work.
2) Continue to support other UNIX platforms on a best-effort basis, and add a disclaimer regarding `ENOBUFS` on non-Linux platforms. I don't mind doing this, and people would likely still find it useful in the common case, but it may surprise people who try to run much larger amounts of data through it.

I'm happy to do either one, and I would appreciate suggestions from you and from @Freaky. Which of the above would you prefer, or do you have another alternative to suggest?

**Comment by lnicola** [comment]
My gut reaction is to go with 1. People might not see the warning, of they might try it, see that it works, then shrug and use it until it breaks down some six months later (or when they run a `make -j16` at the same time).

You shouldn't listen to me, though. I'm using neither your crate nor a BSD so whatever you pick won't affect me and I'll incline towards the conservative choice: it wasn't working on BSD a week ago (because it didn't exist), so nothing will be lost if your drop support for those. Maybe you could add a `broken-on-bsd` feature.

Good point about the connection-oriented sockets. Bummer.

**Comment by Freaky** [comment]
2's my gut reaction.  The blocking thing can be mitigated by setting a big enough socket buffer - not perfectly, but probably enough for it to be useful in a pinch - which seems to have been your motivation for making it in the first place.

Sadly Rust doesn't appear to offer a nice interface for setting this like it does for sockets, so it'd be fiddly for io-mux to do itself.

**Comment by joshtriplett** [comment]
Based on both of your feedback, I think I'm going to keep the portable path, but add a feature flag required to enable compilation on non-Linux, and a disclaimer that makes it clear the limitations there.

Thank you both for the help.

**Comment by joshtriplett** [comment]
Done. Please see the detailed new portability note at the top of src/lib.rs in io-mux 1.0.1.

**Comment by lnicola** [comment]
I wonder, would it make sense to use `sendfile` to pipe the streams into the corresponding Unix client sockets?

**Comment by joshtriplett** [comment]
@lnicola Not sure what you mean by that. Pipe *which* streams into the corresponding UNIX client sockets?

**Comment by lnicola** [comment]
Make one socket for each stream (like now) but instead of using the client sockets as stdout and stderr call sendfile directly with the original fds as source and the sockets as destination.

You might need to use pipes. So one pipe + one UDS for each sender.

**Comment by lnicola** [comment]
Well, I guess that will break the ordering, never mind.

**Comment by joshtriplett** [comment]
@lnicola Right, that would defeat the purpose of using io-mux, and would no longer give an advantage over using two pipes directly. (And it wouldn't prevent this problem either, as far as I can tell.)

**Comment by lnicola** [comment]
Yeah, I should read up on how sendfile works. Is it just a read+write loop? Is there a fast path for "you're writing to this thing with a sendfile running on it, I'll just write to the destination directly instead"?

The BSD implementation might be different from the Linux one, perhaps in exciting ways:

> Armed with dtruss, OS X's system call profiling tool, I observed that the sendfile() system call returns successfully, but doesn't actually cause the client to receive the data until some kind of Apache timeout kicks in and calls shutdown() on the socket. This causes response to have a delay of ~5 seconds.

**Comment by joshtriplett** [comment]
On Fri, Feb 07, 2020 at 12:36:44AM -0800, Laurențiu Nicola wrote:
> Yeah, I should read up on how sendfile works. Is it just a read+write loop? Is there a fast path for "you're writing to this thing with a sendfile running on it, I'll just write to the destination directly instead"?

sendfile is a bit more optimized than a read-write loop (and it stays in
the kernel). But there's no logic to skip from a sendfile source to
destination. The Linux-specific splice syscall is the closest to that:
it moves pages of memory directly from one file/pipe/etc to another. You
still have to perform the syscall, but it can eliminate some copies.
